/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * accueil.java
 *
 * Created on 1 juin 2020, 21:03:31
 */

package health_frames;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import picos_health.Fonctions;
import picos_health.bdd;

/**
 *
 * @author iamwinner
 */
public class accueil extends javax.swing.JFrame {
    ResultSet rs,r1;
    bdd db;
    String  username1, password1;

    /** Creates new form accueil */
    public accueil() {

        db = new bdd(new Fonctions().BASE, new Fonctions().DB_USERNAME, new Fonctions().PASSWORD, new Fonctions().IPHOST, new Fonctions().PORT);
        initComponents();
        //this.setBackground(new Color(0,0,0,0));
         //btnConnect.setBackground(new Color(64,167,227));
         //CENTRAGE DU FORMULAIRE
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        boxUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boxPass = new javax.swing.JPasswordField();
        btnConnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connexion");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 48));
        jLabel2.setText("CONNEXION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        boxUser.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14));
        boxUser.setBorder(null);
        boxUser.setOpaque(false);
        jPanel1.add(boxUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 340, 40));

        jSeparator1.setForeground(new java.awt.Color(64, 167, 227));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 340, 10));

        jSeparator2.setForeground(new java.awt.Color(64, 167, 227));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 340, 10));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12));
        jLabel3.setForeground(new java.awt.Color(143, 143, 143));
        jLabel3.setText("Mot de passe");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12));
        jLabel4.setForeground(new java.awt.Color(143, 143, 143));
        jLabel4.setText("Nom d'utilisateur");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        boxPass.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14));
        boxPass.setBorder(null);
        boxPass.setOpaque(false);
        jPanel1.add(boxPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 340, 40));

        btnConnect.setBackground(new java.awt.Color(64, 167, 227));
        btnConnect.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12));
        btnConnect.setForeground(new java.awt.Color(255, 255, 255));
        btnConnect.setText("Se connecter");
        btnConnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConnectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConnectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConnectMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConnectMousePressed(evt);
            }
        });
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });
        jPanel1.add(btnConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 340, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectMouseClicked
        // TODO add your handling code here:
        btnConnect.setBackground(new Color(0,120,215));
    }//GEN-LAST:event_btnConnectMouseClicked

    private void btnConnectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectMouseEntered
        // TODO add your handling code here:
         btnConnect.setBackground(new Color(0,120,215));
    }//GEN-LAST:event_btnConnectMouseEntered

    private void btnConnectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectMouseExited
        // TODO add your handling code here:
         btnConnect.setBackground(new Color(64,167,227));
    }//GEN-LAST:event_btnConnectMouseExited

    private void btnConnectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnConnectMousePressed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        rs = db.requeteSelectAllP("utilisateur", "login='" + boxUser.getText() + "' AND pass='" + boxPass.getText() + "'");
                                  //TABLE        //colonne 1                       //colonne2
        try{
            while(rs.next()){
                username1 = rs.getString("login");
                password1 = rs.getString("pass");
            }
        }catch(SQLException ex){
            Logger.getLogger(accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(username1 == null && password1 == null){
            JOptionPane.showMessageDialog(this, "Le nom d'utilisateur ou le mot de passe est incorrect");
        }else{
            menu lemenu = new menu();
            lemenu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField boxPass;
    private javax.swing.JTextField boxUser;
    private javax.swing.JButton btnConnect;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
