/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ajout_Patient.java
 *
 * Created on 30 juil. 2020, 16:34:21
 */

package health_frames;
import java.awt.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import picos_health.Fonctions;
import picos_health.bdd;
/**
 *
 * @author iamwinner
 */
public class Ajout_Patient extends javax.swing.JFrame {
//DELCRATIONS
    ResultSet rs;
    bdd db;
    /** Creates new form Ajout_Patient */
    public Ajout_Patient() {
        db = new bdd(new Fonctions().BASE, new Fonctions().DB_USERNAME, new Fonctions().PASSWORD, new Fonctions().IPHOST, new Fonctions().PORT);
        initComponents();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boxNom = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        boxPNoms = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        comGroupe = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        boxNumTel = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btnAjout = new javax.swing.JButton();

        setTitle("Nouveau patient");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(14, 22, 33));
        jPanel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(82, 136, 193));
        jLabel1.setFont(new java.awt.Font("Open Sans Light", 0, 30));
        jLabel1.setForeground(new java.awt.Color(82, 136, 193));
        jLabel1.setText("NOUVEAU PATIENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 22, -1, -1));

        boxNom.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        boxNom.setForeground(new java.awt.Color(255, 255, 255));
        boxNom.setBorder(null);
        boxNom.setOpaque(false);
        boxNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNomActionPerformed(evt);
            }
        });
        jPanel1.add(boxNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 280, 40));

        jSeparator1.setForeground(new java.awt.Color(82, 136, 193));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 280, 10));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel2.setForeground(new java.awt.Color(143, 143, 143));
        jLabel2.setText("Nom");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        boxPNoms.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        boxPNoms.setForeground(new java.awt.Color(255, 255, 255));
        boxPNoms.setBorder(null);
        boxPNoms.setOpaque(false);
        boxPNoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPNomsActionPerformed(evt);
            }
        });
        jPanel1.add(boxPNoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 280, 40));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel3.setForeground(new java.awt.Color(143, 143, 143));
        jLabel3.setText("Groupe sanguin");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(82, 136, 193));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 280, 10));

        comGroupe.setBackground(new java.awt.Color(14, 22, 33));
        comGroupe.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        comGroupe.setForeground(new java.awt.Color(255, 255, 255));
        comGroupe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B", "O+", "O-", "AB+", "AB-" }));
        comGroupe.setBorder(null);
        comGroupe.setOpaque(false);
        comGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comGroupeActionPerformed(evt);
            }
        });
        jPanel1.add(comGroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 280, 40));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel4.setForeground(new java.awt.Color(143, 143, 143));
        jLabel4.setText("Prénoms");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        boxNumTel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        boxNumTel.setForeground(new java.awt.Color(255, 255, 255));
        boxNumTel.setBorder(null);
        boxNumTel.setOpaque(false);
        boxNumTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNumTelActionPerformed(evt);
            }
        });
        boxNumTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                boxNumTelKeyTyped(evt);
            }
        });
        jPanel1.add(boxNumTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 280, 40));

        jSeparator3.setForeground(new java.awt.Color(82, 136, 193));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 280, 10));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel5.setForeground(new java.awt.Color(143, 143, 143));
        jLabel5.setText("Numéro de téléphone");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        btnAjout.setBackground(new java.awt.Color(82, 136, 193));
        btnAjout.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        btnAjout.setForeground(new java.awt.Color(255, 255, 255));
        btnAjout.setText("AJOUTER");
        btnAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnAjout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 280, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNomActionPerformed

    private void boxPNomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPNomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxPNomsActionPerformed

    private void boxNumTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNumTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNumTelActionPerformed

    private void btnAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutActionPerformed
        // TODO add your handling code here:
        //DECLARATIONS
        String nom = boxNom.getText();
        String prenoms = boxPNoms.getText();
        String numero = boxNumTel.getText();
        String groupe = comGroupe.getSelectedItem().toString();
        if(nom.trim().equals("") || prenoms.trim().equals("") || numero.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs!");
        }else if(numero.length() != 8){
            JOptionPane.showMessageDialog(this, "Le numéro de téléphone est incorrect!");
        }else{
            //REQUETE DE SELECTION DU MEDECIN
            String predicat = "`nomPatient`= '"+boxNom.getText()+ "' AND `prenomPatient`= '"+boxPNoms.getText()+"'";
            rs = db.requeteSelectAllP("patient", predicat);
            try {
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Le patient existe déja!");
                } else {
                    String[] colonne = {nom, prenoms, groupe, numero};
                    System.out.println(db.requeteInsertion("patient", colonne));
                    JOptionPane.showMessageDialog(this, "Patient ajouté avec succès!");
                    boxNom.setText("");
                    boxPNoms.setText("");
                    boxNumTel.setText("");
                    comGroupe.setSelectedIndex(0);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Ajout_Patient.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_btnAjoutActionPerformed

    private void boxNumTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxNumTelKeyTyped
        // TODO add your handling code here:
         if(!Character.isDigit(evt.getKeyChar()))//VERIFICATION DU NUMERO DE TELEPHONE
            evt.consume();
    }//GEN-LAST:event_boxNumTelKeyTyped

    private void comGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comGroupeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comGroupeActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajout_Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxNom;
    private javax.swing.JTextField boxNumTel;
    private javax.swing.JTextField boxPNoms;
    private javax.swing.JButton btnAjout;
    private javax.swing.JComboBox comGroupe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

}
