/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ajout_Medecin.java
 *
 * Created on 28 juil. 2020, 20:24:36
 */

package health_frames;

import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import picos_health.Fonctions;
import picos_health.bdd;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author iamwinner
 */
public class Ajout_Medecin extends javax.swing.JFrame {
    //DELCRATIONS
    ResultSet rs;
    bdd db;
    /** Creates new form Ajout_Medecin */
    public Ajout_Medecin() {
         db = new bdd(new Fonctions().BASE, new Fonctions().DB_USERNAME, new Fonctions().PASSWORD, new Fonctions().IPHOST, new Fonctions().PORT);
        initComponents();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        boxPrenoms = new javax.swing.JTextField();
        boxNom = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        boxNumTel = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAjout = new javax.swing.JButton();

        setTitle("Nouveau medecin");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(14, 22, 33));

        jLabel1.setBackground(new java.awt.Color(82, 136, 193));
        jLabel1.setFont(new java.awt.Font("Open Sans Light", 0, 36));
        jLabel1.setForeground(new java.awt.Color(82, 136, 193));
        jLabel1.setText("NOUVEAU MEDECIN");

        jSeparator1.setBackground(new java.awt.Color(14, 22, 33));
        jSeparator1.setForeground(new java.awt.Color(82, 136, 193));

        boxPrenoms.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14));
        boxPrenoms.setForeground(new java.awt.Color(255, 255, 255));
        boxPrenoms.setBorder(null);
        boxPrenoms.setOpaque(false);

        boxNom.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14));
        boxNom.setForeground(new java.awt.Color(255, 255, 255));
        boxNom.setBorder(null);
        boxNom.setOpaque(false);

        jSeparator2.setBackground(new java.awt.Color(14, 22, 33));
        jSeparator2.setForeground(new java.awt.Color(82, 136, 193));

        boxNumTel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14));
        boxNumTel.setForeground(new java.awt.Color(255, 255, 255));
        boxNumTel.setBorder(null);
        boxNumTel.setOpaque(false);
        boxNumTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                boxNumTelKeyTyped(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(14, 22, 33));
        jSeparator3.setForeground(new java.awt.Color(82, 136, 193));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel2.setForeground(new java.awt.Color(143, 143, 143));
        jLabel2.setText("Nom");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel3.setForeground(new java.awt.Color(143, 143, 143));
        jLabel3.setText("Prénoms");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel4.setForeground(new java.awt.Color(143, 143, 143));
        jLabel4.setText("Numéro de téléphone");

        btnAjout.setBackground(new java.awt.Color(82, 136, 193));
        btnAjout.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        btnAjout.setForeground(new java.awt.Color(255, 255, 255));
        btnAjout.setText("AJOUTER");
        btnAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(boxNom, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                                    .addGap(6, 6, 6))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap(46, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                .addComponent(boxPrenoms, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                .addComponent(boxNumTel, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                .addComponent(btnAjout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                            .addGap(46, 46, 46)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxNom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(boxPrenoms, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutActionPerformed
        String nomMedecin;
        if(boxNom.getText().equals("") || boxPrenoms.getText().equals("") || boxNumTel.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs!");
        }else if(boxNumTel.getText().length() != 8){
            JOptionPane.showMessageDialog(this, "Le numéro de téléphone est invalide!");
        }
        else{
          //REQUETE DE SELECTION DU MEDECIN
            String predicat = "`nomMedecin`= '"+boxNom.getText()+ "' AND `prenomMedecin`= '"+boxPrenoms.getText()+"'";
            rs = db.requeteSelectAllP("medecin", predicat);
            try {
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Le medecin existe déja!");
                }else{
                    String[] infos = {boxNom.getText(), boxPrenoms.getText(), boxNumTel.getText()};
                    System.out.println(db.requeteInsertion("medecin", infos));
                    JOptionPane.showMessageDialog(this, "Médecin ajouté avec succèes!");
                    boxNom.setText("");
                    boxPrenoms.setText("");
                    boxNumTel.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Ajout_Medecin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnAjoutActionPerformed

    private void boxNumTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxNumTelKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()))//VERIFICATION DU NUMERO DE TELEPHONE
            evt.consume();
    }//GEN-LAST:event_boxNumTelKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajout_Medecin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxNom;
    private javax.swing.JTextField boxNumTel;
    private javax.swing.JTextField boxPrenoms;
    private javax.swing.JButton btnAjout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

}
