/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ajout_Prescription.java
 *
 * Created on 31 juil. 2020, 08:02:34
 */

package health_frames;
import java.awt.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import picos_health.Fonctions;
import picos_health.bdd;
/**
 *
 * @author iamwinner
 */
public class Ajout_Prescription extends javax.swing.JFrame {
    ResultSet rs;
    ResultSet rs1;
    bdd db;
    /** Creates new form Ajout_Prescription */
    public Ajout_Prescription() {
        db = new bdd(new Fonctions().BASE, new Fonctions().DB_USERNAME, new Fonctions().PASSWORD, new Fonctions().IPHOST, new Fonctions().PORT);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         this.boxPosologie.setBackground(new Color(14,22,33));
        //SELECTION DES INFOS DE LA CONSULTATION
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comConsult = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comMedoc = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        boxPosologie = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Nouvelle prescription");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(14, 22, 33));

        jLabel1.setBackground(new java.awt.Color(82, 136, 193));
        jLabel1.setFont(new java.awt.Font("Open Sans Light", 0, 30));
        jLabel1.setForeground(new java.awt.Color(82, 136, 193));
        jLabel1.setText("NOUVELLE PRESCRIPTION");

        comConsult.setBackground(new java.awt.Color(14, 22, 33));
        comConsult.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        comConsult.setForeground(new java.awt.Color(255, 255, 255));
        comConsult.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jLabel2.setForeground(new java.awt.Color(143, 143, 143));
        jLabel2.setText("Consultation");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jLabel3.setForeground(new java.awt.Color(143, 143, 143));
        jLabel3.setText("Médicament");

        comMedoc.setBackground(new java.awt.Color(14, 22, 33));
        comMedoc.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        comMedoc.setForeground(new java.awt.Color(255, 255, 255));
        comMedoc.setOpaque(false);

        jScrollPane1.setBackground(new java.awt.Color(14, 22, 33));
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        boxPosologie.setColumns(20);
        boxPosologie.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        boxPosologie.setForeground(new java.awt.Color(255, 255, 255));
        boxPosologie.setRows(4);
        jScrollPane1.setViewportView(boxPosologie);

        jSeparator1.setForeground(new java.awt.Color(82, 136, 193));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jLabel4.setForeground(new java.awt.Color(143, 143, 143));
        jLabel4.setText("Posologie");

        jButton1.setBackground(new java.awt.Color(82, 136, 193));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PRESCRIRE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(comConsult, 0, 304, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(comMedoc, 0, 304, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.boxPosologie.setBackground(new Color(14,22,33));
        //SELECTION DES INFOS DE LA CONSULTATION
        String[] colonne = {"numConsult", "CONCAT_WS('     ', dateConsult, nomMedecin) AS date_et_medecin"};
        rs = db.requeteSelectP(colonne, "medecin, consultation", "medecin.numMedecin = consultation.numMedecin");
        
        try {
            while (rs.next()) {
                String numConsult = rs.getString("numConsult").toString();
                String dateConsult = rs.getString("date_et_medecin").toString();
                comConsult.addItem(numConsult+" " + dateConsult);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ajout_Prescription.class.getName()).log(Level.SEVERE, null, ex);
        }
        //SELECTION DES MEDOCS
        String[] colonnes = {"codeMedoc", "nomMedoc"};
        rs1 = db.requeteSelect(colonnes, "medicament");
        try {
            while (rs1.next()) {
                String nomMedoc = rs1.getString("nomMedoc");
                String numMedoc = rs1.getString("codeMedoc");
                comMedoc.addItem(numMedoc+" "+nomMedoc);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ajout_Prescription.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String combox1 = comConsult.getSelectedItem().toString();//COMBO CONSULTATION
        String[] tableau = combox1.split(" ");
        String numConsult = tableau[0];

        String combox2 = comMedoc.getSelectedItem().toString();//COMBO MEDICAMENT
        String[] tableau1 = combox2.split(" ");
        String numMedeoc = tableau1[0];

        //INSERTION
        if(boxPosologie.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs!");
        }else{
            String posologie = boxPosologie.getText();
            String[] colonnes = {numConsult, numMedeoc, posologie};
            System.out.println(db.requeteInsertion("prescription", colonnes));
            JOptionPane.showMessageDialog(this, "Prescription ajoutée avec succès!");
            boxPosologie.setText("");
            comConsult.setSelectedIndex(0);
            comMedoc.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajout_Prescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea boxPosologie;
    private javax.swing.JComboBox comConsult;
    private javax.swing.JComboBox comMedoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
