/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Liste_consultation.java
 *
 * Created on 31 juil. 2020, 21:06:07
 */

package health_frames;
import java.awt.*;
import java.sql.*;
import java.util.logging.*;
import javax.swing.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import picos_health.*;

/**
 *
 * @author iamwinner
 */
public class Liste_consultation extends javax.swing.JFrame {
    ResultSet rs;
    bdd db;
    /** Creates new form Liste_consultation */
    public Liste_consultation() {
        db = new bdd(new Fonctions().BASE, new Fonctions().DB_USERNAME, new Fonctions().PASSWORD, new Fonctions().IPHOST, new Fonctions().PORT);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         table();
    }
     public void table(){
        String[] colonne = {"numConsult", "dateConsult", "nomMedecin", "nomPatient", "prenomPatient", "motifConsult"};
        String nomTable = "consultation C, medecin M, patient P";
        String predicat = "P.numPatient = C.numPatient AND C.numMedecin = M.numMedecin";
        rs = db.requeteSelectP(colonne, nomTable, predicat);
        this.tble_consult.setModel(new ResultSetTableModel(rs));
    }
     public void actualiser(){
         boxMotif.setText("");
         comMedecin.setSelectedIndex(0);
         comPatient.setSelectedIndex(0);
     }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble_consult = new javax.swing.JTable();
        comMedecin = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comPatient = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        boxMotif = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();

        setTitle("Liste des consultations");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(14, 22, 33));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Open Sans Light", 0, 30));
        jLabel1.setForeground(new java.awt.Color(82, 136, 193));
        jLabel1.setText("GESTION DES CONSULTATIONS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        tble_consult.setBackground(new java.awt.Color(14, 22, 33));
        tble_consult.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        tble_consult.setForeground(new java.awt.Color(82, 136, 192));
        tble_consult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numéro", "Date", "Nom du médecin", "Nom du patient", "Prénoms du patient", "Motif"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tble_consult.setDragEnabled(true);
        tble_consult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tble_consultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble_consult);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 71, 708, 160));

        comMedecin.setBackground(new java.awt.Color(14, 22, 33));
        comMedecin.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        comMedecin.setForeground(new java.awt.Color(255, 255, 255));
        comMedecin.setBorder(null);
        comMedecin.setPreferredSize(new java.awt.Dimension(0, 19));
        jPanel1.add(comMedecin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 330, 40));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jLabel2.setForeground(new java.awt.Color(143, 143, 143));
        jLabel2.setText("Médecin traitant");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jLabel4.setForeground(new java.awt.Color(143, 143, 143));
        jLabel4.setText("Motif");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        comPatient.setBackground(new java.awt.Color(14, 22, 33));
        comPatient.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        comPatient.setForeground(new java.awt.Color(255, 255, 255));
        comPatient.setBorder(null);
        comPatient.setPreferredSize(new java.awt.Dimension(0, 19));
        jPanel1.add(comPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 330, 40));

        boxMotif.setBackground(new java.awt.Color(14, 22, 33));
        boxMotif.setColumns(20);
        boxMotif.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        boxMotif.setRows(5);
        boxMotif.setOpaque(false);
        jScrollPane2.setViewportView(boxMotif);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 330, 100));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jLabel5.setForeground(new java.awt.Color(143, 143, 143));
        jLabel5.setText("Patient");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jButton1.setBackground(new java.awt.Color(82, 136, 193));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Modifier");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 160, 40));

        jButton2.setBackground(new java.awt.Color(14, 22, 33));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jButton2.setForeground(new java.awt.Color(82, 136, 193));
        jButton2.setText("Supprimer");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(82, 136, 193)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 330, 140, 40));

        jb3.setText("jButton3");
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });
        jPanel1.add(jb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String num_patient = "";
       String num_medecin = "";

       String combox2 = comPatient.getSelectedItem().toString();//RECUPERATION DU COMBOBOX PATIENT
       String[] tableau1 = combox2.split(" ");//DECOUPAGE EN TABLEAU AVEC SUPPRESION DES ESPACES
       String nomP = tableau1[0];//RECUPERATION DU NOM QUI SE TROUVE FORCEMENT A L'INDEX 0

       String predicat1 = "nomPatient='"+ nomP+"' AND prenomPatient='";//CONCATENATION
       for(int i=1; i <= tableau1.length - 1;i++){
               predicat1 += tableau1[i];//AJOUT DES PRENOMS CONTENUS DANS LE TABLEAU ET SUPPRESSION DE L'ESPACE A LA FIN
               if(i < tableau1.length - 1){
                   predicat1 += " ";
               }
       }
     
       predicat1 += "'";//FIN DU PREDICAT
       String[] colonne1 = {"numPatient"};
       rs = db.requeteSelectP(colonne1, "patient", predicat1);
        try {
            while (rs.next()) {
                num_patient = rs.getString("numPatient");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Liste_consultation.class.getName()).log(Level.SEVERE, null, ex);
        }

       String combox1 = comMedecin.getSelectedItem().toString();//RECUPERATION DU COMBOBOX MEDECIN
       //RECUPERATION DU NOM QUI SE TROUVE FORCEMENT A L'INDEX 0

       String predicat = "nomMedecin = '"+ combox1 +"'";
       String[] colonne = {"numMedecin"};
       rs = db.requeteSelectP(colonne, "medecin", predicat);
        try {
            while (rs.next()) {
                num_medecin = rs.getString("numMedecin").toString();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Liste_consultation.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(boxMotif.getText().equals("")){
             
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs!");
        }else{
    
            String[] colonnes = {"numMedecin", "numPatient", "motifConsult"};
            String[] infos = {num_medecin, num_patient, boxMotif.getText()};
            String num_consult = String.valueOf(tble_consult.getValueAt(tble_consult.getSelectedRow(), 0));
            predicat = "numConsult='" + num_consult + "'";
            //MIS A JOUR
            System.out.println(db.requeteUpdte("consultation", colonnes, infos, predicat));
            JOptionPane.showMessageDialog(this, "Modification effectuée!");
            actualiser();
            table();
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String numConsult = String.valueOf(tble_consult.getValueAt(tble_consult.getSelectedRow(), 0));
        if(JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer l'enregistrement", "Avertissement", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            db.requeteDelete("prescription", "numConsult="+numConsult);
        }else{
            return;
        }
        table();
}//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.boxMotif.setBackground(new Color(14,22,33));

        String[] colonne = {"nomMedecin"};//REQUETE SELECTION DES MEDECINS
        rs = db.requeteSelect(colonne, "medecin");//RESULTSET
        String nomMedecin = "";
        try {
            while (rs.next()){ //LECTURE DES RESULTAT
                nomMedecin = rs.getString("nomMedecin").toString();
                comMedecin.addItem(nomMedecin);//AJOUT DES ELEMENT DE LA REQUETE
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ajout_consultation.class.getName()).log(Level.SEVERE, null, ex);
        }

        String prenomPatient ="";
        String nomPatient="";
        String[] colonnes = {"nomPatient", "prenomPatient"};//REQUETE SELECTION DES PATIENTS
        rs = db.requeteSelect(colonnes, "patient");//RESULTSET
        try {
            while (rs.next()){ //LECTURE DES RESULTAT
                nomPatient = rs.getString("nomPatient").toString();
                prenomPatient = rs.getString("prenomPatient").toString();
                comPatient.addItem(nomPatient.toUpperCase() + " " + prenomPatient);//AJOUT DES ELEMENT DE LA REQUETE
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ajout_consultation.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    private void tble_consultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tble_consultMouseClicked
        // TODO add your handling code here:
        boxMotif.setText(String.valueOf(tble_consult.getValueAt(tble_consult.getSelectedRow(), 5)));
        comMedecin.setSelectedItem(String.valueOf(tble_consult.getValueAt(tble_consult.getSelectedRow(), 2)));
        comPatient.setSelectedItem(String.valueOf(tble_consult.getValueAt(tble_consult.getSelectedRow(), 3)) + " " + String.valueOf(tble_consult.getValueAt(tble_consult.getSelectedRow(), 4)));
    }//GEN-LAST:event_tble_consultMouseClicked

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        // TODO add your handling code here:
        try {
                Class.forName("com.mysql.jdbc.Driver");
                //ConnexionBase connect = new ConnexionBase();
                Connection connect;
                String urlbase = "jdbc:mysql://localhost:3306/picos_health";
                connect = DriverManager.getConnection(urlbase, "root", "");

                JasperDesign jdesign = JRXmlLoader.load("E:\\Files\\PROJET\\Picos Health\\Picos_Health\\src\\report1.jrxml");

                String query= "SELECT * FROM `patient`";
                JRDesignQuery updateQuery = new JRDesignQuery();
                updateQuery.setText(query);

                jdesign.setQuery(updateQuery);

            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jreport, null, connect);
            //JasperExportManager.exportReportToPdfFile(jasperPrint, "products.pdf");
            JasperViewer.viewReport(jasperPrint);


        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jb3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Liste_consultation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea boxMotif;
    private javax.swing.JComboBox comMedecin;
    private javax.swing.JComboBox comPatient;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb3;
    private javax.swing.JTable tble_consult;
    // End of variables declaration//GEN-END:variables

}
