/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Liste_Patient.java
 *
 * Created on 31 juil. 2020, 09:23:32
 */

package health_frames;
import java.sql.*;
import java.awt.*;
import javax.swing.JOptionPane;
import picos_health.bdd;
import picos_health.Fonctions;
import picos_health.ResultSetTableModel;
/**
 *
 * @author iamwinner
 */
public class Liste_Patient extends javax.swing.JFrame {
    ResultSet rs;
    bdd db;
    /** Creates new form Liste_Patient */
    public Liste_Patient() {
        db = new bdd(new Fonctions().BASE, new Fonctions().DB_USERNAME, new Fonctions().PASSWORD, new Fonctions().IPHOST, new Fonctions().PORT);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         table();
    }

    //FONCTION DE CHARGEMENT DES DONNEES DE LA TABLE
    public void table(){
        rs = db.requeteSelectAll("patient");
        this.tble_patient.setModel(new ResultSetTableModel(rs));
    }
    //VIDAGE DES CHAMPS
    public void actualiser(){
        boxNom.setText("");
        boxPNoms.setText("");
        boxNumTel.setText("");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble_patient = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        boxNom = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        boxPNoms = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        comGroupe = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        boxNumTel = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Liste des patients");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(14, 22, 33));

        jLabel1.setFont(new java.awt.Font("Open Sans Light", 0, 36));
        jLabel1.setForeground(new java.awt.Color(82, 136, 193));
        jLabel1.setText("LISTE DES PATIENTS");

        tble_patient.setBackground(new java.awt.Color(14, 22, 33));
        tble_patient.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        tble_patient.setForeground(new java.awt.Color(82, 136, 193));
        tble_patient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numéro", "Nom", "Prénoms", "Groupe sanguin", "Numéro de téléphone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tble_patient.setGridColor(new java.awt.Color(255, 255, 255));
        tble_patient.setOpaque(false);
        tble_patient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tble_patientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble_patient);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel2.setForeground(new java.awt.Color(143, 143, 143));
        jLabel2.setText("Nom");

        boxNom.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        boxNom.setForeground(new java.awt.Color(255, 255, 255));
        boxNom.setBorder(null);
        boxNom.setOpaque(false);
        boxNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNomActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(82, 136, 193));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel4.setForeground(new java.awt.Color(143, 143, 143));
        jLabel4.setText("Prénoms");

        boxPNoms.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        boxPNoms.setForeground(new java.awt.Color(255, 255, 255));
        boxPNoms.setBorder(null);
        boxPNoms.setOpaque(false);
        boxPNoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPNomsActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(82, 136, 193));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel3.setForeground(new java.awt.Color(143, 143, 143));
        jLabel3.setText("Groupe sanguin");

        comGroupe.setBackground(new java.awt.Color(14, 22, 33));
        comGroupe.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        comGroupe.setForeground(new java.awt.Color(255, 255, 255));
        comGroupe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "O+", "O-" }));
        comGroupe.setBorder(null);
        comGroupe.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel5.setForeground(new java.awt.Color(143, 143, 143));
        jLabel5.setText("Numéro de téléphone");

        boxNumTel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        boxNumTel.setForeground(new java.awt.Color(255, 255, 255));
        boxNumTel.setBorder(null);
        boxNumTel.setOpaque(false);
        boxNumTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNumTelActionPerformed(evt);
            }
        });
        boxNumTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                boxNumTelKeyTyped(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(82, 136, 193));

        jButton1.setBackground(new java.awt.Color(82, 136, 193));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Modifier");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(14, 22, 33));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(82, 136, 193));
        jButton2.setText("Supprimer");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(82, 136, 193)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(404, 404, 404))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(comGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(boxNom, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(boxPNoms, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(boxNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(29, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(boxNom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addComponent(boxPNoms, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(comGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addComponent(boxNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNomActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_boxNomActionPerformed

    private void boxPNomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPNomsActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_boxPNomsActionPerformed

    private void boxNumTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNumTelActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_boxNumTelActionPerformed

    private void boxNumTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxNumTelKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()))//VERIFICATION DU NUMERO DE TELEPHONE
            evt.consume();
}//GEN-LAST:event_boxNumTelKeyTyped

    private void tble_patientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tble_patientMouseClicked
        // TODO add your handling code here:
        //AFFECTATION DES VALEURS DANS LES CHAMPS
        boxNom.setText(String.valueOf(tble_patient.getValueAt(tble_patient.getSelectedRow(), 1)));
        boxPNoms.setText(String.valueOf(tble_patient.getValueAt(tble_patient.getSelectedRow(), 2)));
        boxNumTel.setText(String.valueOf(tble_patient.getValueAt(tble_patient.getSelectedRow(), 4)));
        comGroupe.setSelectedItem(String.valueOf(tble_patient.getValueAt(tble_patient.getSelectedRow(), 3)));
    }//GEN-LAST:event_tble_patientMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(boxNom.getText().equals("") || boxPNoms.getText().equals("") || boxNumTel.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs!");
        }else if(boxNumTel.getText().length() != 8){
            JOptionPane.showMessageDialog(this, "Numéro de téléphone incorrect!");
        }else{
            String[] colonnes = {"nomPatient", "prenomPatient", "grpSanguin", "numTelPatient"};
            String[] infos = {boxNom.getText(), boxPNoms.getText(), comGroupe.getSelectedItem().toString(), boxNumTel.getText()};
            String num_Pa = String.valueOf(tble_patient.getValueAt(tble_patient.getSelectedRow(), 0));
            String predicat = "numPatient='" + num_Pa + "'";
            //MIS A JOUR
            System.out.println(db.requeteUpdte("patient", colonnes, infos, predicat));
            JOptionPane.showMessageDialog(this, "Modification effectuée!");
            actualiser();
            table();
            comGroupe.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String num_Pa = String.valueOf(tble_patient.getValueAt(tble_patient.getSelectedRow(), 0));
        if(JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer l'enregistrement", "Avertissement", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            db.requeteDelete("patient", "numPatient="+num_Pa);
        }else{
            return;
        }
        table();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Liste_Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxNom;
    private javax.swing.JTextField boxNumTel;
    private javax.swing.JTextField boxPNoms;
    private javax.swing.JComboBox comGroupe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tble_patient;
    // End of variables declaration//GEN-END:variables

}
