/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Liste_Medicament.java
 *
 * Created on 31 juil. 2020, 18:57:21
 */

package health_frames;

import java.sql.*;
import picos_health.*;
import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author iamwinner
 */
public class Liste_Medicament extends javax.swing.JFrame {
    ResultSet rs;
    bdd db;

    /** Creates new form Liste_Medicament */
    public Liste_Medicament() {
        db = new bdd(new Fonctions().BASE, new Fonctions().DB_USERNAME, new Fonctions().PASSWORD, new Fonctions().IPHOST, new Fonctions().PORT);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         table();
    }
    public void table(){
        rs = db.requeteSelectAll("medicament");
        this.tble_medoc.setModel(new ResultSetTableModel(rs));
    }
    public void actualiser(){
        boxNom.setText("");
        boxType.setText("");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble_medoc = new javax.swing.JTable();
        boxRech = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        boxType = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        boxNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Liste des médicament");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(14, 22, 33));

        jLabel1.setFont(new java.awt.Font("Open Sans Light", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(82, 136, 193));
        jLabel1.setText("GESTION DES MEDICAMENTS");

        tble_medoc.setBackground(new java.awt.Color(14, 22, 33));
        tble_medoc.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        tble_medoc.setForeground(new java.awt.Color(82, 136, 193));
        tble_medoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numéro", "Nom", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tble_medoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tble_medocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble_medoc);

        boxRech.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14));
        boxRech.setForeground(new java.awt.Color(255, 255, 255));
        boxRech.setBorder(null);
        boxRech.setOpaque(false);
        boxRech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxRechMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boxRechMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boxRechMouseExited(evt);
            }
        });
        boxRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRechActionPerformed(evt);
            }
        });
        boxRech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                boxRechKeyTyped(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(14, 22, 33));
        jSeparator4.setForeground(new java.awt.Color(82, 136, 193));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 2, 11));
        jLabel5.setForeground(new java.awt.Color(143, 143, 143));
        jLabel5.setText("Recherche");

        jSeparator5.setBackground(new java.awt.Color(14, 22, 33));
        jSeparator5.setForeground(new java.awt.Color(82, 136, 193));

        boxType.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14));
        boxType.setForeground(new java.awt.Color(255, 255, 255));
        boxType.setBorder(null);
        boxType.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel4.setForeground(new java.awt.Color(143, 143, 143));
        jLabel4.setText("Type");

        jSeparator3.setBackground(new java.awt.Color(14, 22, 33));
        jSeparator3.setForeground(new java.awt.Color(82, 136, 193));

        boxNom.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14));
        boxNom.setForeground(new java.awt.Color(255, 255, 255));
        boxNom.setBorder(null);
        boxNom.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12));
        jLabel3.setForeground(new java.awt.Color(143, 143, 143));
        jLabel3.setText("Nom");

        jButton1.setBackground(new java.awt.Color(82, 136, 193));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Modifier");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(14, 22, 33));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jButton2.setForeground(new java.awt.Color(82, 136, 193));
        jButton2.setText("Supprimer");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(82, 136, 193)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxRech, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxNom, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(boxType, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxRech, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)))
                .addGap(1, 1, 1)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boxNom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxRechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxRechMouseClicked
        // TODO add your handling code here:
        jLabel5.setVisible(false);
}//GEN-LAST:event_boxRechMouseClicked

    private void boxRechMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxRechMouseEntered
        jLabel5.setVisible(false);
        // TODO add your handling code here:
}//GEN-LAST:event_boxRechMouseEntered

    private void boxRechMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxRechMouseExited
        // TODO add your handling code here:
        jLabel5.setVisible(true);
}//GEN-LAST:event_boxRechMouseExited

    private void boxRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRechActionPerformed
        // TODO add your handling code here:
        rs = db.requeteSelectAllP("medicament", "nomMedoc LIKE '%"+ boxRech.getText()+"%' OR typeMedoc LIKE '%" + boxRech.getText()+"%'");
        tble_medoc.setModel(new ResultSetTableModel(rs));
}//GEN-LAST:event_boxRechActionPerformed

    private void boxRechKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxRechKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_boxRechKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(boxNom.getText().equals("") || boxType.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs!");
        }else{
            String[] colonnes = {"nomMedoc", "typeMedoc"};
            String[] infos = {boxNom.getText(), boxType.getText()};
            String num_M = String.valueOf(tble_medoc.getValueAt(tble_medoc.getSelectedRow(), 0));
            String predicat = "codeMedoc='" + num_M + "'";
            //MIS A JOUR
            System.out.println(db.requeteUpdte("medicament", colonnes, infos, predicat));
            JOptionPane.showMessageDialog(this, "Modification effectuée!");
            actualiser();
            table();
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String num_M = String.valueOf(tble_medoc.getValueAt(tble_medoc.getSelectedRow(), 0));
        if(JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer l'enregistrement", "Avertissement", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            db.requeteDelete("medicament", "codeMedoc="+num_M);
        }else{
            return;
        }
        table();
}//GEN-LAST:event_jButton2ActionPerformed

    private void tble_medocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tble_medocMouseClicked
        // TODO add your handling code here:
        boxNom.setText(String.valueOf(tble_medoc.getValueAt(tble_medoc.getSelectedRow(), 1)));
        boxType.setText(String.valueOf(tble_medoc.getValueAt(tble_medoc.getSelectedRow(), 2)));
    }//GEN-LAST:event_tble_medocMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Liste_Medicament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxNom;
    private javax.swing.JTextField boxRech;
    private javax.swing.JTextField boxType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable tble_medoc;
    // End of variables declaration//GEN-END:variables

}
