/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Liste_Prescription.java
 *
 * Created on 31 juil. 2020, 19:18:07
 */

package health_frames;

import java.awt.*;
import java.sql.*;
import java.util.logging.*;
import javax.swing.*;
import picos_health.*;

/**
 *
 * @author iamwinner
 */
public class Liste_Prescription extends javax.swing.JFrame {
    ResultSet rs;
    bdd db;
    /** Creates new form Liste_Prescription */
    public Liste_Prescription() {
        db = new bdd(new Fonctions().BASE, new Fonctions().DB_USERNAME, new Fonctions().PASSWORD, new Fonctions().IPHOST, new Fonctions().PORT);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         table();
    }
    public void table(){
        String[] colonne = {"num_pres", "dateConsult", "nomMedoc", "posologie"};
        String nomTable = "consultation C, medicament M, prescription P";
        String predicat = "C.numConsult = P.numConsult AND P.codeMedoc = M.codeMedoc";
        rs = db.requeteSelectP(colonne, nomTable, predicat);
        this.tble_pres.setModel(new ResultSetTableModel(rs));
    }
     
     public void actualiser(){
         comMedoc.setSelectedIndex(0);
         boxPosologie.setText("");
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble_pres = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        boxPosologie = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        comMedoc = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Liste des prescriptions");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(14, 22, 33));

        jLabel1.setFont(new java.awt.Font("Open Sans Light", 0, 30));
        jLabel1.setForeground(new java.awt.Color(82, 136, 193));
        jLabel1.setText("GESTION DES PRESCRIPTIONS");

        tble_pres.setBackground(new java.awt.Color(14, 22, 33));
        tble_pres.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        tble_pres.setForeground(new java.awt.Color(82, 136, 193));
        tble_pres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numéro presciption", "Date consultation", "Médicament prescrit", "Posologie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tble_pres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tble_presMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble_pres);

        jScrollPane2.setBackground(new java.awt.Color(14, 22, 33));
        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        boxPosologie.setBackground(new java.awt.Color(14, 22, 33));
        boxPosologie.setColumns(20);
        boxPosologie.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        boxPosologie.setRows(4);
        boxPosologie.setBorder(null);
        boxPosologie.setOpaque(false);
        jScrollPane2.setViewportView(boxPosologie);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jLabel4.setForeground(new java.awt.Color(143, 143, 143));
        jLabel4.setText("Posologie");

        comMedoc.setBackground(new java.awt.Color(14, 22, 33));
        comMedoc.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        comMedoc.setForeground(new java.awt.Color(255, 255, 255));
        comMedoc.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jLabel3.setForeground(new java.awt.Color(143, 143, 143));
        jLabel3.setText("Médicament");

        jButton1.setBackground(new java.awt.Color(82, 136, 193));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Modifier");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(14, 22, 33));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13));
        jButton2.setForeground(new java.awt.Color(82, 136, 193));
        jButton2.setText("Supprimer");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(82, 136, 193)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                            .addComponent(jLabel1))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.boxPosologie.setBackground(new Color(14,22,33));
        String[] colonnes = {"nomMedoc"};
        rs = db.requeteSelect(colonnes, "medicament");
        try {
            while (rs.next()) {
                String nomMedoc = rs.getString("nomMedoc");
                comMedoc.addItem(nomMedoc);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ajout_Prescription.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void tble_presMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tble_presMouseClicked
        // TODO add your handling code here:
        boxPosologie.setText(String.valueOf(tble_pres.getValueAt(tble_pres.getSelectedRow(), 3)));
        comMedoc.setSelectedItem(String.valueOf(tble_pres.getValueAt(tble_pres.getSelectedRow(), 2)));
    }//GEN-LAST:event_tble_presMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(boxPosologie.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs!");
        }else{
            String[] colonnes = {"codeMedoc", "posologie"};
            String[] col = {"codeMedoc"};
            String nomMedoc = comMedoc.getSelectedItem().toString();
            rs = db.requeteSelectP(col, "medicament", "nomMedoc = '"+nomMedoc+"'");
            String num_medoc ="";
            try {
                while (rs.next()) {
                    num_medoc = rs.getString("codeMedoc");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Liste_Prescription.class.getName()).log(Level.SEVERE, null, ex);
            }
            String[] infos = {num_medoc, boxPosologie.getText()};
            String num_pres = String.valueOf(tble_pres.getValueAt(tble_pres.getSelectedRow(), 0));
            String predicat = "num_pres='" + num_pres + "'";
            //MIS A JOUR
            System.out.println(db.requeteUpdte("prescription", colonnes, infos, predicat));
            JOptionPane.showMessageDialog(this, "Modification effectuée!");
            actualiser();
            table();
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String num_pres = String.valueOf(tble_pres.getValueAt(tble_pres.getSelectedRow(), 0));
        if(JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer l'enregistrement", "Avertissement", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            db.requeteDelete("prescription", "num_pres="+num_pres);
        }else{
            return;
        }
        table();
}//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Liste_Prescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea boxPosologie;
    private javax.swing.JComboBox comMedoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tble_pres;
    // End of variables declaration//GEN-END:variables

}
